version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - goconst
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - wsl
  settings:
    exhaustive:
      default-signifies-exhaustive: false
    goconst:
      min-len: 2
      min-occurrences: 5
    gocyclo:
      min-complexity: 16
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
