# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envexample < Formula
  desc "Generate a .env.example from an env struct"
  homepage "https://github.com/miniscruff/envexample"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miniscruff/envexample/releases/download/v0.2.0/envexample_0.2.0_darwin_amd64.tar.gz"
      sha256 "c0ea1ab4229a0809e834f76bc510843408d6d35f346169a15bddd888ae29ab51"

      define_method(:install) do
        bin.install "envexample"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miniscruff/envexample/releases/download/v0.2.0/envexample_0.2.0_darwin_arm64.tar.gz"
      sha256 "b13912e5dcb718c51efcec25a8f8d5527ff19bbebf88531fc657ea5122bc4c2c"

      define_method(:install) do
        bin.install "envexample"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/miniscruff/envexample/releases/download/v0.2.0/envexample_0.2.0_linux_amd64.tar.gz"
      sha256 "54be05a56d7f6e08eafcecdcf282ef735e6bb8d60f9932511002489ac950daa8"
      define_method(:install) do
        bin.install "envexample"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miniscruff/envexample/releases/download/v0.2.0/envexample_0.2.0_linux_arm64.tar.gz"
      sha256 "7789b9220d23ed8a29c35878992fd1a2333f210d8d00a696d4994ab87260ddab"
      define_method(:install) do
        bin.install "envexample"
      end
    end
  end
end
