name: release

on:
  push:
    branches: [ main ]
    paths: [ CHANGELOG.md ]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Get the latest version
      id: latest
      uses: miniscruff/changie-action@v1
      with:
        version: latest
        args: latest

    - name: Add env vars
      run: |
        echo GORELEASER_CURRENT_TAG=${{ steps.latest.outputs.output }} >> $GITHUB_ENV

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: --rm-dist --release-notes=.changes/${{ steps.latest.outputs.output }}.md --skip-validate --debug
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

