name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.github/'
    - '.changes/'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '.github/'
    - '.changes/'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.23'

    - name: Check out code
      uses: actions/checkout@v4

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        # Required: the version of golangci-lint is required and must be specified
        # without patch version: we always use the latest patch version.
        version: 'v2.0'

    - name: Test
      run: go test -coverprofile=c.out ./...

