name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.github/'
    - '.changes/'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '.github/'
    - '.changes/'

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Check out code
      uses: actions/checkout@v4

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Required: the version of golangci-lint is required and must be specified
        # without patch version: we always use the latest patch version.
        version: 'v1.52'

    - name: Test
      run: go test -coverprofile=c.out ./...

    - name: Coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./c.out
        fail_ci_if_error: true
